project_name: grouping
builds:
  - env: [CGO_ENABLED=0]
    main: ./cmd/grouping/main.go
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - format_overrides:
    - goos: windows
      format: zip
nfpms:
- maintainer: toriwasa <toriwasa@gmail.com>
  description: This is a tool to group sequence of numbers.
  homepage: https://github.com/toriwasa/
  license: MIT
  formats:
  - deb
  - rpm
  - apk
